export const KEY_SWITCH = {
  R0: "GENERIC_R0",
  R1: "GENERIC_R1",
  R2: "GENERIC_R2",
  R3: "GENERIC_R3",
  R4: "GENERIC_R4",
  BACKSPACE: "BACKSPACE",
  ENTER: "ENTER",
  SPACE: "SPACE",
  SHIFT: "GENERIC_R4",
};
